### ISSUE TITLE
[WEEK2] Efficient Off-Policy Meta-Reinforcement Learning via Probabilistic Context Variables Q&A

### ISSUE THREAD

**Issue by SooDevv** [PaperReviewStudy/prstudy4ml#3]
If you have any questions, please ask it in this issue

**Comment by deephoony** [comment]
이 논문에서의 Motivation과 어떻게 해결했는지 간단한 요약 부탁드립니다!

**Comment by dongminlee94** [comment]
1. Inference network의 objective에서 KL term을 다른 term으로 바꾸는게 가능한가? e.g. JSD

**Comment by dongminlee94** [comment]
1. 어떠한 ture posterior p(z|c)를 estimate하는 Inference network q_\phi (z|c)를 modeling하는 방법으로 VAE를 사용했기 때문에 objective의 KL term을 다른 term으로 사용하는 것은 불가능할 것 같습니다.  만약 VAE가 아닌 GAN처럼 adversarial하게 min max를 취하는 방법으로 모델링을 했다면 objective가 달라질 수는 있을 것 같습니다.
