### ISSUE TITLE
[WEEK2] Bi-Directional Cascade Network for Perceptual Edge Detection Q&A

### ISSUE THREAD

**Issue by SooDevv** [PaperReviewStudy/prstudy4ml#4]
If you have any questions, please ask it in this issue

**Comment by SooDevv** [comment]
@bocharm 보찬님 질문 요약해서 업로드좀 부탁드려요..

**Comment by deephoony** [comment]
1. semantic segmentation과 perceptual edge detection은 용도가 어떻게 다른가요?
2. evaluation metric이 어떻게 되나요? (복잡한 경우, 참고할 수 있는 링크 부탁드리겠습니다.)

**Comment by MoMentum99** [comment]
1. 각 스케일마다 나오는 prediction map 을 다 더한게 Y^ 이면 이걸 인퍼런스타임에 그대로 쓰나요? 그걸 다 더하면 contour edge 개념이랑 좀 다른거 같아서요

2. bi-direction 인데 두 방향에 대해 같은 conv weight를 공유하나요? 관련된 intuition 이 있을까요??

3. (2번이랑 조금 연결되는 질문인데) 각 스케일마다 prediction map 을 그냥 channel-wise 로 더하는 걸 봤을때, 모델안에서 pooling은 안하는거 같은데 맞나요? 그렇다면 s2d 는 dilated-conv 를 계속 쌓으면서 receptive field를 키워서 global feature를 잡는게 납득이 가는데 그 반대 방향은 어떻게 d2s 라고 할 수 있는지 잘 이해가 안됩니다ㅠ 가르침을 주세요
